#!/usr/bin/env bash
set -Eeuo pipefail

# Executed on the EC2 host through SSM. The host uses its instance profile for
# ECR and SSM access; no static AWS credentials are used. EC2 is a single point
# of failure with manual-only scaling; this target is unsuitable where HA or
# elastic scaling is required. Keep durable container data in named volumes.
APP_DIR=/opt/app
COMPOSE_FILE=docker-compose.prod.yml
ENVIRONMENT=${1:?usage: deploy.sh <environment> <image-tag> <region> <ecr-url> <host-url> <host-ip> <domains>}
IMAGE_TAG=${2:?missing image tag}
AWS_REGION=${3:?missing AWS region}
ECR_REPOSITORY_URL=${4:?missing ECR repository URL}
HOST_URL=${5:?missing host URL}
HOST_IP=${6:?missing host IP}
SITE_DOMAINS=${7:-}

case "$ENVIRONMENT" in
  dev|prod) ;;
  *) echo "Unsupported environment: $ENVIRONMENT" >&2; exit 2 ;;
esac
[[ "$IMAGE_TAG" =~ ^[A-Za-z0-9_.-]+$ ]] || { echo "Invalid image tag" >&2; exit 2; }
[[ "$ECR_REPOSITORY_URL" == */* ]] || { echo "Invalid ECR repository URL" >&2; exit 2; }
[[ "$HOST_URL" == https://* || "$HOST_URL" == http://* ]] || { echo "Invalid host URL" >&2; exit 2; }

cd "$APP_DIR"
chmod 700 "$APP_DIR"
mkdir -p deploy/nginx

# Emit only the contractually allowed parameter names. Values are never logged,
# and env files are private to root. An empty web.env is intentional.
write_service_env() {
  local service=$1
  shift
  local path="/notes-app-f308/${ENVIRONMENT}/${service}/"
  local response
  response=$(aws ssm get-parameters-by-path \
    --region "$AWS_REGION" --with-decryption --recursive \
    --path "$path" --output json)
  SERVICE_NAME="$service" ALLOWED_KEYS="$*" PARAMETER_JSON="$response" python3 - <<'PY'
import json
import os
from pathlib import Path

service = os.environ["SERVICE_NAME"]
allowed = set(os.environ["ALLOWED_KEYS"].split())
parameters = json.loads(os.environ["PARAMETER_JSON"]).get("Parameters", [])
values = {}
for parameter in parameters:
    key = parameter["Name"].rstrip("/").split("/")[-1]
    if key in allowed:
        values[key] = parameter["Value"]
missing = allowed - values.keys()
if missing:
    raise SystemExit(f"Missing required SSM parameters for {service}: {', '.join(sorted(missing))}")
content = "".join(
    f"{key}={json.dumps(values[key], ensure_ascii=False).replace('$', '$$')}\n"
    for key in sorted(allowed)
)
path = Path(f"/opt/app/{service}.env")
path.write_text(content, encoding="utf-8")
path.chmod(0o600)
PY
}

write_service_env web
write_service_env api DB_HOST DB_NAME DB_PASSWORD DB_USER
write_service_env db MYSQL_DATABASE MYSQL_PASSWORD MYSQL_RANDOM_ROOT_PASSWORD MYSQL_USER

# The nginx files are platform-maintained, not generated by this deploy.
cp deploy/nginx/http.conf deploy/nginx/active.conf
chmod 644 deploy/nginx/active.conf

export AWS_REGION ECR_REPOSITORY_URL IMAGE_TAG
compose() {
  docker compose --env-file /dev/null -f "$COMPOSE_FILE" "$@"
}

previous_tag=""
if [[ -f .current-image-tag ]]; then
  previous_tag=$(<.current-image-tag)
elif [[ -f .previous-image-tag ]]; then
  previous_tag=$(<.previous-image-tag)
fi

rollback() {
  local status=$?
  trap - ERR
  if [[ -n "$previous_tag" && "$previous_tag" != "$IMAGE_TAG" ]]; then
    echo "Deployment failed; rolling back to image tag $previous_tag." >&2
    IMAGE_TAG=$previous_tag
    export IMAGE_TAG
    compose pull web api || true
    compose up -d || true
    compose exec -T proxy nginx -s reload || true
    if ! curl --fail --silent --show-error --max-time 10 "${HOST_URL%/}/healthz"; then
      echo "Rollback was attempted but the health endpoint is still failing." >&2
    fi
  else
    echo "Deployment failed and no previous image tag is available for rollback." >&2
  fi
  exit "$status"
}

# Confirm DNS before certificate issuance, and accept any matching resolved
# address rather than depending on DNS answer ordering.
if [[ -n "$SITE_DOMAINS" ]]; then
  IFS=',' read -r -a domains <<< "$SITE_DOMAINS"
  cert_exists=0
  if compose exec -T certbot test -s /etc/letsencrypt/live/app/fullchain.pem >/dev/null 2>&1; then
    cert_exists=1
  fi
  if (( ! cert_exists )); then
    for domain in "${domains[@]}"; do
      domain=${domain//[[:space:]]/}
      [[ -n "$domain" ]] || continue
      if ! getent ahostsv4 "$domain" | awk -v wanted="$HOST_IP" '$1 == wanted { found=1 } END { exit !found }'; then
        resolved=$(getent ahostsv4 "$domain" | awk '{print $1}' | sort -u | paste -sd, - || true)
        echo "Certificate issuance stopped: $domain must resolve to $HOST_IP (currently ${resolved:-unresolved}). Update DNS and retry." >&2
        exit 1
      fi
    done
    compose up -d proxy certbot
    certbot_args=(certbot certonly --webroot -w /var/www/certbot --cert-name app)
    for domain in "${domains[@]}"; do
      domain=${domain//[[:space:]]/}
      [[ -n "$domain" ]] && certbot_args+=(-d "$domain")
    done
    certbot_args+=(--agree-tos --register-unsafely-without-email --non-interactive)
    compose exec -T certbot "${certbot_args[@]}"
  fi
  if compose exec -T certbot test -s /etc/letsencrypt/live/app/fullchain.pem; then
    cp deploy/nginx/https.conf deploy/nginx/active.conf
    chmod 644 deploy/nginx/active.conf
  else
    echo "Certificate was not created at /etc/letsencrypt/live/app; refusing HTTPS deployment." >&2
    exit 1
  fi
elif compose exec -T certbot test -s /etc/letsencrypt/live/app/fullchain.pem >/dev/null 2>&1; then
  cp deploy/nginx/https.conf deploy/nginx/active.conf
  chmod 644 deploy/nginx/active.conf
fi

trap rollback ERR

# Authenticate on-host with the EC2 instance role, then deploy the immutable SHA.
registry=${ECR_REPOSITORY_URL%%/*}
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$registry"
compose pull web api
compose up -d
compose exec -T proxy nginx -s reload

attempt=0
while (( attempt < 30 )); do
  if curl --fail --silent --show-error --max-time 10 "${HOST_URL%/}/healthz"; then
    if [[ -n "$previous_tag" && "$previous_tag" != "$IMAGE_TAG" ]]; then
      printf '%s\n' "$previous_tag" > .previous-image-tag
      chmod 600 .previous-image-tag
    fi
    printf '%s\n' "$IMAGE_TAG" > .current-image-tag
    chmod 600 .current-image-tag
    trap - ERR
    echo "Deployment succeeded: $IMAGE_TAG"
    exit 0
  fi
  attempt=$((attempt + 1))
  sleep 10
done

echo "Health check failed through proxy at ${HOST_URL%/}/healthz after 300 seconds." >&2
false
